# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
        - name: Automatic Changelog Generator
  # You may pin to the exact commit or the version.
  # uses: CharMixer/auto-changelog-action@72ee445303a13d3fb4ac02a11b5813e70ec3d3d2
  uses: CharMixer/auto-changelog-action@v1.1
  with:
    # Username of the owner of target GitHub repo (default: extracted from $GITHUB_REPOSITORY)
    user: # optional
    # Name of project on GitHub (default: extracted from $GITHUB_REPOSITORY)
    project: # optional
    # Limit pull requests to the release branch, such as master or release (required, default: master)
    release_branch: # optional, default is master
    # Output file. To print to STDOUT instead, use blank as path. (required, default: CHANGELOG.md)
    output: # optional, default is CHANGELOG.md
    # Optional base file to append generated changes to (default: HISTORY.md)
    base: # optional
    # To make more than 50 requests per hour your GitHub token is required. You can generate it at: https://github.com/settings/tokens/new<Paste>
    token: # optional
    # Changelog will start after specified tag.
    since_tag: # optional
    # Changelog will end before specified tag.
    due_tag: # optional
    # Changelog will exclude specified tags (comma seperated)
    exclude_tags: # optional
    # Issues with the specified labels will be excluded from changelog. Default is "duplicate,question,invalid,wontfix".
    exclude_labels: # optional
    # Date format. Default is %Y-%m-%d
    date_format: # optional
    # Put the unreleased changes in the specified release number.
    future_release: # optional
